---
title: "brainstorming"
output: pdf_document
date: "2025-06-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Main Method

```{r}
library(stringr)
library(readr)
library(dplyr)
library(gtools)


#' Takes losssum data from:
#'  https://genome.senckenberg.de/download/TOGA/human_hg38_reference/
#'  and repackages data to a .tsv where every GENE ID is on col 1 and every subsequent col's rows contains the presence or absence of GENE ID of that same row. Also writes csv containing every species obtained in script, such that ever row = new species.
#' @author Tyler gruver
geneCollector <- function(){
  # Access losssum.tsv
  setwd("~/meyerLab/psuedogeneCollector/data")
  files <- list.files(
    path = ".", # "~/meyerLab/psuedogeneCollector/data", 
    recursive=TRUE, 
    pattern = "loss_summ_data",
    full.names=TRUE)
  
  species_gene <- getData(files)
  allSpecies <- data.frame(speciesList = names(species_gene))
  genes <- updateUniqueGenes(species_gene)
  GeneIDToPresencePerSpecies<-mergeData(species_gene, genes)
  #View(GeneIDToPresencePerSpecies)
  write_tsv(GeneIDToPresencePerSpecies, path = "psuedo.tsv")
  write_csv(allSpecies, path = "ListOfSpecies")
  
}


#' Obtains and cleans loss_summ_data
#' @param files --> Vector containing absolute paths to every instance of loss_summ_data
#' @return A list formatted as a dictionary --> key = character (species name), value = df (clean loss_summ_data)
#' @author Tyler gruver
getData <- function(files){
  species_gene <- list() #key == species name, value == .tsv file containing losssum data
   counter <- 0

  for(i in 1:length(files)){
    temp <- str_locate_all(files[i], "/")[[1]] #temp returns a list of matrixes. [[1]] grabs the matrix  at position 1... temp will only ever be a list of length 1 
    
    #Setting key-value pairs
    name <- substring(files[i], temp[3, 1] +1 , temp[4, 1] -1)
    key <- paste(name , sep = " ")
    value <- cleanData(files[i]) #returns clean .tsv
    species_gene[[key]] <- value
  }  
  

  return(species_gene)
}

#' cleans loss_summ_data
#' @param f --> Vector containing absolute paths to a single instance of loss_summ_data
#' @return A df --> Clean loss_summ_data
#' @author Tyler gruver
cleanData <- function(f){
  df <- read_tsv(f, show_col_types = FALSE)
  clean_df <- df[df$PROJECTION == "GENE",]
  return(clean_df[, -1])
}

#' Creates a list of unique genes seen under every instance of loss_summ_data
#' @param files --> Vector containing absolute paths to a single instance of loss_summ_data 
#' @return A list containing every unique gene under every instance of loss_summ_data
#' @author Tyler gruver    
updateUniqueGenes <- function(species_gene){
  genes <- character(length=0)
  cleanListOfAllGenes <- getGenesFromSpecies(species_gene)
  
  for(genesList in cleanListOfAllGenes) {
    genes <- union(genes, genesList)  # performs set union operation on genes character vector AND df[,1] column subset.
    
  }
  
  return(genes)
}

#' Parses through species_gene key to obtain all genes that belong to the second col of every VALUE to each KEY within dictionary 
#' @param species_gene, genes --> species_gene is parsed. genes is unnecessary, too lazy to remove :) 
#' @return A list where every element is the character vector of genes.
#' @author Tyler gruver
getGenesFromSpecies <- function(species_gene, genes){
  listOfAllGenes<- unname(species_gene)
  return(listOfAllGenes[[1]][,1])
}

#' Merges species VALUES  against list of genes sorted numerically in ascending order
#' @param sg --> Dictionary where key = species name, value = a tibble where col 1 = geneID, col 2 = PRESENCE  
#' @return data.frame to write to tsv
#' @author Tyler gruver
mergeData <- function(sg, genes){
   genes <- mixedsort(genes)
   df_merged <- data.frame(species = genes) #Converts genes to a dataframe to prepare to merge
   
for (i in seq_along(sg)) { #iterate every even index in sg (AKA every key)
  species_df <- sg[[i]] #grab tibble of the key being iterated on and convert to data frame to prepare for merge
  colnames(species_df) <- c("gene", "label") #define a name for these data frames so that I can specify which column to merge. Merge against "species", which contains genes of [ith] species using "gene".  

  merged <- merge(df_merged, species_df, by.x = "species", by.y = "gene", all.x = TRUE)

  # Save label column and rename it to species
  df_merged[[ names(sg)[i] ]] <- merged$label
}
   
  for (col in names(df_merged)[-1]) {  
    for (i in seq_len(nrow(df_merged))) {
      df_merged[i, col] <- switch(
      df_merged[i, col],
      "I" = 1,
      "UL" = 1,
      "PI" = 1,
       "L" = 0,
      "M" = NA,
      "PM" = NA,
      "PG" = NA,
      NA  # default is NA if unmatched or NULL
    )
  }
}
  return(df_merged)
  
}

geneCollector()
```
